version: '3.8'
services:
  php-apache-environment:
    container_name: havoc-middleman
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
